add gcs-connector-1.6.10-hadoop2.jar to git because latest version is incompatible with hail's current hadoop version (see https://hail.zulipchat.com/#narrow/stream/123009-Hail-0.2E1.20support/topic/java.2Elang.2ENoSuchMethodError.3Aorg.2Eapache.2Ehadoop.2Efs.2EFileStatus)